### ISSUE TITLE
Wrong daily values

### ISSUE THREAD

**Issue by duboisst** [chriscamicas/gazdebordeaux-ha#1]
Hi,
This integration is great but I noticed a minor issue:
on last november, from 20 to 26 the daily consumptions are wrong with very high values.

In HA:
![image](https://github.com/chriscamicas/gazdebordeaux-ha/assets/6418017/392a97c9-9b0e-44b6-b70f-1d8864c52fc2)

In Gaz de Bordeaux site:
![image](https://github.com/chriscamicas/gazdebordeaux-ha/assets/6418017/f033f755-f06b-4e98-a0be-3aade32b5a63)

**Comment by chriscamicas** [comment]
Thank you for your feedback, and for using my integration :)
That's really weird, I checked on my side, and I don't have this issue (aka "it works on my machine" :p)

1. Could you please share the yaml of your panel in HA, I'd like to check what statistics and options you have chosen ?
2. The datas I'm using come from https://life.gazdebordeaux.fr/understand/analysis (which is different website, and API from https://espaceclient.gazdebordeaux.fr/dashboard) could you check on that particular website if your data are correct ? It could be on their side rather than on the integration per say

Let me know, thank you

**Comment by duboisst** [comment]
1. This is the Energy dashboard, I can't see its yaml
Here is the configuration
![image](https://github.com/chriscamicas/gazdebordeaux-ha/assets/6418017/373681fd-ff97-47a5-8c89-c63b969da058)
However, I've seen that if I add the following card in a custom dashboard, values of Gaz de Bordeaux consumption (état) are good and values of Gaz de Bordeaux consumption (variation) are corresponding to the values displayed in the energy dashboard 
![image](https://github.com/chriscamicas/gazdebordeaux-ha/assets/6418017/765095b0-85b4-4fbf-96a9-627c7889aae5)
`chart_type: line
period: day
type: statistics-graph
entities:
  - gazdebordeaux:energy_consumption
stat_types:
  - state
  - change
days_to_show: 90
`
2. The data I see on https://life.gazdebordeaux.fr/understand/analysis are the same that the ones on https://espaceclient.gazdebordeaux.fr/dashboard

**Comment by chriscamicas** [comment]
Awesome thanks for the detailed analysis, I'll look into it
I guess is related to the Energy Dashboard sensor ...

**Comment by chriscamicas** [comment]
duplicate #2
